AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda REST API with MySQL
Resources:
  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/createUser.handler
      Runtime: nodejs18.x
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /users
            Method: post
  GetUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/getUser.handler
      Runtime: nodejs18.x
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: get
  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/updateUser.handler
      Runtime: nodejs18.x
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: put
  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/deleteUser.handler
      Runtime: nodejs18.x
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /users/{id}
            Method: delete
